### PR TITLE
Fix some cached records being overwritten

### PR DESCRIPTION
**Pull request by Marlamin**
See comments for problem description. Not sure if best solution, but has been working in production for a few months now.

(Last PR before local repo is up to date with this one, I swear)

### CODE REVIEW

**Comment by barncastle** [comment]
Is this in the situation that Blizzard does multiple actions to the same record? e.g.
1. Update record 123 for table X
2. Invalidate record 123 from table X
3. Update record 123 for table X

**Comment by Marlamin** [comment]
Yeah, but only for non-pushID records (so not technically hotfixes, just cached rows). Because there's no push ID for those we can't really prioritize them, but I'd say the ones with data should always beat the ones without data. There were issues with WoW.tools missing TACT keys in caches as Blizzard likes to invalidate those after use these days.

**Comment by barncastle** [comment]
Gotcha. Would it be worth making this applicable to all tables in case it does start to apply to more or is that risky?

Also might be worth moving `records.Any(r => r.IsValid && r.PushId == -1 && r.DataSize > 0)` outside the loop to it's own variable.

**Comment by Marlamin** [comment]
Did that on one of my initial attempts but that got a bit slow for some reason which is why it's only limited to tactkey for now. Will retry in a bit to see if it still happens.

**Comment by Marlamin** [comment]
I think this might be the fastest as it only does the LINQ stuff because it ONLY gets to that else if the record it's trying to add already exists.

**Comment by barncastle** [comment]
I assume the slowdown is because it keeps querying if one of these cases exists for each invalid record? Since it's a generic check you could test it before the loop starts then the loop only contains a boolean check.
```c#
var records = _reader.GetRecords(dbReader.TableHash).OrderBy(x => x.PushId);

var shouldDelete = !records.Any(r => r.IsValid && r.PushId == -1 && r.DataSize > 0);
// OR just for TACTKey
var shouldDelete = dbReader.TableHash != 3744420815 || !records.Any(r => r.IsValid && r.PushId == -1 && r.DataSize > 0);

foreach (var row in records)
...
   else if(shouldDelete)
       storage.Remove(row.RecordId)
```

**Comment by Marlamin** [comment]
Kept the TACTKey check for now as I wasn't able to reproduce the issue on the other cached DBs.

This (except for a pushID filter which I feel is too WoW.tools specific) is now what is running on WoW.tools in production. Glad to finally be mostly synced up again after this gets merged. :D

**Comment by barncastle** [comment]
Looks good to me! Sorry for the rewrite...

Maybe we could abstract hotfixing a bit so people can filter what exactly is applied instead of just blasting everything at the base storage? I assume what you're refering to is [this](https://github.com/Marlamin/DBCDumpHost/blob/e81aba68d50f70180e167df0b091b7790e262cd5/DBCDumpHost/Services/DBCManager.cs#L100)? Probably should be a new issue :)

**Comment by Marlamin** [comment]
Yep! Merging. Will need to open up an issue for that at some point for sure.

**Pull request merged**
