### PR TITLE
Fix missing encrypted records

### PR DESCRIPTION
**Pull request by Marlamin**
Issue found and fix submitted by Nieriel.

Currently assumes if recordData == 0 that it should be skipped, but recordData -can- be 0, with non-recordData still having data.

### CODE REVIEW

**Comment by Marlamin** [comment]
e.g. a row can have only fields with 0 in it, but still be a valid row by purely being a copy row. These would get skipped in the current situation as only record data itself gets checked. Fix checks the whole section instead of just the record data part of it. It adds a handful of rows for AnimKit, SceneScript, SpellCooldowns, SpellLevels and SpellVisualKit.

**Comment by barncastle** [comment]
Makes sense. Just checked to see if there was any indicator we could use but I think scanning the entire section is the only way to go. - Horrible file format!

Would there be any valid reason that record data would be non-zero whilst the remainder of the section would be zero filled? I.e. should the `Array.TrueForAll(recordsData, x => x == 0)` line be used still as part of the `completelyZero` check?

Edit: Thinking about it, you could just read the next int32 as this must be non-zero if the recorddata is zero as it will be either: the record id (index/copydata), the sparse offset or the number of refdata records.

**Comment by Marlamin** [comment]
I think you lost me there, can you propose those changes?

**Comment by barncastle** [comment]
Sorry was waffling a bit yesterday. 

My first comment was that we may need to keep `Array.TrueForAll(recordsData, x => x == 0)` in the situation the section is already fully read. I'm not sure if it exists but potentially a sparse table could be entirely self contained in it's `recordsData` without needing additional data.

Then my second thought was that if there is additional data then we'd only need to check the first entry of the next segment to validate if this section is to be used or not.

<details>
  <summary>Stupidly Verbose Code</summary>

  ```c#
  // skip encrypted sections => has tact key + record data is zero filled
  if (section.TactKeyLookup != 0 && Array.TrueForAll(recordsData, x => x == 0))
  {
      bool completelyZero = false;
      if (section.IndexDataSize > 0 || section.CopyTableCount > 0)
      {
          // this will be the record id from m_indexData or m_copyData
          // if this is zero then the id for this record will be zero which is invalid
          completelyZero = reader.ReadInt32() == 0;
          reader.BaseStream.Position -= 4;
      }
      else if (section.OffsetMapIDCount > 0)
      {
          // this will be the first m_sparseEntries entry
          // confirm it's size is not zero otherwise it is invalid
          completelyZero = reader.Read<SparseEntry>().Size == 0;
          reader.BaseStream.Position -= 6;
      }
      else
      {
          // there is no additional data and recordsData is already known to be zeroed
          // therefore the record will have an id of zero which is invalid
          completelyZero = true;
      }
  
      if (completelyZero)
      {
          previousRecordCount += section.NumRecords;
          continue;
      }
  }
  ```
</details>

**Comment by Marlamin** [comment]
Yeah, that's fair and seems fine to me. I'll add that in in a bit, thanks.

**Comment by Marlamin** [comment]
Added in the proposed code 1:1 as it seems to work, kept the comments because we're going to be very confused in the future otherwise. :D

**Comment by barncastle** [comment]
Good thinking batman! I'm also considering if we need to check all `recordsData` or just the first int32 of that too... 
But if it works and you're happy I'll leave it alone for the time being!

**Comment by Marlamin** [comment]
Seems to work in the tests I just did, same results as the previous code so all good in my book.

**Pull request merged**
